export const bands = [
  {
    id: 1,
    name: "Critical",
    code: "Q1",
    axis: "Important + Urgent",
    focus:
      "Issues that block traffic, revenue or rankings now — fixed immediately.",
  },
  {
    id: 2,
    name: "Reactive",
    code: "Q2",
    axis: "Urgent, Lower Impact",
    focus:
      "Time-sensitive quick wins and corrections with lower strategic weight.",
  },
  {
    id: 3,
    name: "Strategic",
    code: "Q3",
    axis: "Important, Not Urgent",
    focus:
      "Compounding long-term work — content, authority and architecture built over time.",
  },
  {
    id: 4,
    name: "Deferred",
    code: "Q4",
    axis: "Last Tasks",
    focus: "Hygiene, monitoring and polish — valuable but sequenced last.",
  },
];

export const steps = [
  {
    n: 1,
    q: 1,
    title: "Crawl Diagnostics",
    exec: "Surfaces every blocked or orphaned URL blocking revenue.",
    tech: "Server log analysis & render-budget mapping.",
    client: "We find the pages Google can't see.",
  },
  {
    n: 2,
    q: 1,
    title: "Indexation Audit",
    exec: "Quantifies wasted crawl budget vs. money pages.",
    tech: "GSC coverage cross-reference & canonical conflicts.",
    client: "Only your important pages reach the index.",
  },
  {
    n: 3,
    q: 1,
    title: "Robots.txt Calibration",
    exec: "Stops bots draining resources on low-value paths.",
    tech: "Directive engineering & crawl-priority routing.",
    client: "Search engines focus on what sells.",
  },
  {
    n: 4,
    q: 2,
    title: "XML Sitemap Engineering",
    exec: "Accelerates discovery of new revenue pages.",
    tech: "Dynamic sitemap partitions by priority tier.",
    client: "New content is found faster.",
  },
  {
    n: 5,
    q: 3,
    title: "Site Architecture Mapping",
    exec: "Reveals depth & distance from homepage to conversion.",
    tech: "Click-depth graph & orphan-page detection.",
    client: "Visitors reach your offer in fewer clicks.",
  },
  {
    n: 6,
    q: 4,
    title: "URL Structure Normalization",
    exec: "Eliminates duplicate-content dilution of rankings.",
    tech: "Parameter handling & trailing-slash policy.",
    client: "Clean, shareable, consistent links.",
  },
  {
    n: 7,
    q: 1,
    title: "Canonical Tag Deployment",
    exec: "Consolidates link equity to the primary URL.",
    tech: "Self-referential & cross-domain canonical logic.",
    client: "Your authority isn't split across copies.",
  },
  {
    n: 8,
    q: 1,
    title: "Redirect Chain Resolution",
    exec: "Recovers link equity lost in loops & chains.",
    tech: "301/308 mapping & legacy URL reconciliation.",
    client: "No traffic sent to dead ends.",
  },
  {
    n: 9,
    q: 1,
    title: "HTTPS & SSL Verification",
    exec: "Prevents trust & ranking penalties from mixed content.",
    tech: "Certificate audit & HSTS enforcement.",
    client: "Your site is secure and trusted.",
  },
  {
    n: 10,
    q: 2,
    title: "Pagination & Faceted Nav",
    exec: "Controls indexation of filter combinations.",
    tech: "Rel=next/prev & parameter canonicalization.",
    client: "Search stays focused on real products.",
  },
  {
    n: 11,
    q: 3,
    title: "Keyword Topography",
    exec: "Maps demand & revenue potential across the market.",
    tech: "Cluster-level SERP feature analysis.",
    client: "We target the words buyers actually use.",
  },
  {
    n: 12,
    q: 3,
    title: "Search Intent Mapping",
    exec: "Aligns content type to buyer stage for higher conversion.",
    tech: "Intent classification & SERP-pattern modeling.",
    client: "Each page answers the right question.",
  },
  {
    n: 13,
    q: 3,
    title: "Content Gap Analysis",
    exec: "Identifies revenue topics competitors own.",
    tech: "Share-of-voice & gap matrix by cluster.",
    client: "We close the topics you're missing.",
  },
  {
    n: 14,
    q: 4,
    title: "TF-IDF Density Audit",
    exec: "Tunes term weighting for topical authority.",
    tech: "Corpus comparison & entity salience scoring.",
    client: "Your content reads as the expert.",
  },
  {
    n: 15,
    q: 3,
    title: "Semantic Cluster Mapping",
    exec: "Builds topical authority silos that compound.",
    tech: "Entity-relationship graphs & hub-spoke architecture.",
    client: "Your site becomes the reference.",
  },
  {
    n: 16,
    q: 2,
    title: "Title & Meta Optimization",
    exec: "Lifts click-through rate from existing impressions.",
    tech: "CTR modeling & SERP-preview engineering.",
    client: "More clicks from the same rankings.",
  },
  {
    n: 17,
    q: 2,
    title: "Heading Hierarchy Calibration",
    exec: "Strengthens topical signal & accessibility.",
    tech: "H1-H6 semantic structure & outline validation.",
    client: "Clearer pages for users & engines.",
  },
  {
    n: 18,
    q: 3,
    title: "Internal Link Topology",
    exec: "Channels authority to revenue pages.",
    tech: "PageRank flow modeling & anchor distribution.",
    client: "Your best pages get more visibility.",
  },
  {
    n: 19,
    q: 4,
    title: "Content Pruning Protocol",
    exec: "Removes dead weight dragging domain quality.",
    tech: "Quality-score thresholds & consolidation rules.",
    client: "Only earning pages remain.",
  },
  {
    n: 20,
    q: 3,
    title: "Backlink Profile Forensics",
    exec: "Audits the equity & risk in your link graph.",
    tech: "Link-velocity & referring-domain analysis.",
    client: "We know who links to you & why.",
  },
  {
    n: 21,
    q: 1,
    title: "Toxic Link Remediation",
    exec: "Removes penalty risk from spammy links.",
    tech: "Disavow engineering & link-reclamation.",
    client: "Your reputation stays clean.",
  },
  {
    n: 22,
    q: 4,
    title: "Domain Authority Benchmarking",
    exec: "Tracks competitive position vs. market leaders.",
    tech: "Authority-metric correlation & trend tracking.",
    client: "See how you stack up locally.",
  },
  {
    n: 23,
    q: 2,
    title: "Citation & NAP Consistency",
    exec: "Strengthens local trust signals across the web.",
    tech: "Name-address-phone audit & syndication.",
    client: "Customers find the right location.",
  },
  {
    n: 24,
    q: 3,
    title: "Local SEO Grid Mapping",
    exec: "Maps Pretoria rank by geo-grid cell.",
    tech: "Grid-tracking & geo-grid competitor overlay.",
    client: "You rank across the whole city.",
  },
  {
    n: 25,
    q: 2,
    title: "GBP Optimization",
    exec: "Maximizes Maps pack visibility for nearby searches.",
    tech: "Profile completeness & review-velocity strategy.",
    client: "More calls & direction requests.",
  },
  {
    n: 26,
    q: 3,
    title: "Digital PR & Outreach",
    exec: "Earns authority links from relevant publications.",
    tech: "Prospect scoring & pitch-automation pipelines.",
    client: "Your brand gets cited online.",
  },
  {
    n: 27,
    q: 2,
    title: "Brand Mention Tracking",
    exec: "Captures unlinked mentions into equity.",
    tech: "Mention-mining & link-reclamation workflows.",
    client: "Every mention counts.",
  },
  {
    n: 28,
    q: 3,
    title: "Competitor Backlink Infiltration",
    exec: "Replicates the link sources powering rivals.",
    tech: "Competitor link-intersection & gap harvesting.",
    client: "We close the authority gap.",
  },
  {
    n: 29,
    q: 1,
    title: "Core Web Vitals Audit",
    exec: "Fixes the speed signals Google rewards.",
    tech: "LCP/INP/CLS field & lab data correlation.",
    client: "Your site loads instantly.",
  },
  {
    n: 30,
    q: 3,
    title: "Render-Path Optimization",
    exec: "Reduces time-to-interactive for conversion.",
    tech: "Critical CSS & resource-hint injection.",
    client: "Visitors engage sooner.",
  },
  {
    n: 31,
    q: 3,
    title: "JavaScript SEO Diagnostics",
    exec: "Ensures JS-rendered content is indexed.",
    tech: "Dynamic-rendering & SSR audit.",
    client: "Google sees your full site.",
  },
  {
    n: 32,
    q: 1,
    title: "Mobile-First Compliance",
    exec: "Aligns mobile experience with ranking signals.",
    tech: "Mobile parity & tap-target audit.",
    client: "Perfect on every phone.",
  },
  {
    n: 33,
    q: 3,
    title: "Schema & Structured Data",
    exec: "Unlocks rich results & entity understanding.",
    tech: "JSON-LD modeling & validation pipeline.",
    client: "Your listings stand out.",
  },
  {
    n: 34,
    q: 1,
    title: "Page Speed Remediation",
    exec: "Delivers measurable speed gains per template.",
    tech: "Asset budgeting & image-pipeline tuning.",
    client: "Faster pages, more conversions.",
  },
  {
    n: 35,
    q: 3,
    title: "Conversion Path Tracking",
    exec: "Connects SEO traffic to revenue outcomes.",
    tech: "Funnel attribution & event-tracking design.",
    client: "You see what SEO earns.",
  },
  {
    n: 36,
    q: 3,
    title: "Analytics & Attribution",
    exec: "Provides single-source truth for ROI.",
    tech: "GA4 & server-side modeling.",
    client: "Clear numbers, no guesswork.",
  },
  {
    n: 37,
    q: 4,
    title: "Executive Reporting Synthesis",
    exec: "Translates 37 steps into board-ready insight.",
    tech: "Triple-persona dashboard architecture.",
    client: "Reports you actually understand.",
  },
];
